Feature/management page
sabisasam/django-tutorial pull request #43
Opened 2017-09-29 11:48 UTC by dkdndes

2017-09-29 11:49 UTC, dkdndes commented
Don't forget the "pull request" when you finished a feature!

2017-10-02 10:40 UTC, sabisasam requested changes
This version doesn't work properly because of the REDIS_URL part in settings.py. Also it doesn't have the Data Binding version of the management page because I commited that to finnerds/bisa-tutorial. I think at least the REDIS_URL part should be changed.

2017-10-02 10:49 UTC, sabisasam approved these changes

2017-10-02 17:40 UTC, dkdndes commented
Please remind and me to fix it properly. In debug it should be the in-memory option without redis server running ! 

Sent from my iPhone

> On 2. Oct 2017, at 12:40, Sabine <notifications@github.com> wrote:
> 
> @sabisasam requested changes on this pull request.
> 
> This version doesn't work properly because of the REDIS_URL part in settings.py. Also it doesn't have the Data Binding version of the management page because I commited that to finnerds/bisa-tutorial. I think at least the REDIS_URL part should be changed.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-10-10 13:57 UTC, merged